<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-8P6DPJ13" failures="1" tests="3" name="Testcase3" time="62.992" errors="0" timestamp="2025-03-10T20:46:03 IST">
  <testcase classname="com.sevenrmartsupermarket.tests.AdminUsersTest" name="verifyAddUserStatus" time="5.64">
    <failure type="java.lang.AssertionError" message="expected [User Created Successfully] but found [×
Alert!
User Created Successfully]">
      <![CDATA[java.lang.AssertionError: expected [User Created Successfully] but found [×
Alert!
User Created Successfully]
at com.sevenrmartsupermarket.tests.AdminUsersTest.verifyAddUserStatus(AdminUsersTest.java:62)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddUserStatus -->
  <testcase classname="com.sevenrmartsupermarket.tests.AdminUsersTest" name="verifyAdminUserHeader" time="14.065"/>
  <testcase classname="com.sevenrmartsupermarket.tests.AdminUsersTest" name="verifyNewButtonText" time="13.854"/>
</testsuite> <!-- Testcase3 -->
